name: Playwright Tests + Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment, install dependencies
        shell: bash
        run: |
          cd recruitment_task
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        shell: bash
        run: |
          cd recruitment_task
          source venv/bin/activate
          python -m playwright install --with-deps

      - name: Run tests with Allure
        shell: bash
        run: |
          cd recruitment_task
          source venv/bin/activate
          pytest --alluredir=allure-results

      - name: Generate Allure report
        shell: bash
        run: |
          cd recruitment_task
          npm install -g allure-commandline --no-save
          allure generate allure-results --clean -o allure-report

      - name: Add .nojekyll file for GitHub Pages
        shell: bash
        run: |
          cd recruitment_task
          touch allure-report/.nojekyll

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: recruitment_task/allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: recruitment_task/allure-report